version: 2
build:
  image: latest
  apt_packages:
    - cmake
    - gcc@8

sphinx:
  configuration: docs/source/conf.py

submodules:
  include: all

python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .