name: Build And Run Test on Ubuntu

on:
  push:
    branches: [ main ]
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:

  Build_and_Run_UnitTest:
    name: Build and Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: python -m pip install --upgrade wheel

    - name: Install pytest
      run: python -m pip install pytest

    - name: Install filepattern v1
      run: python -m pip install filepattern

    - name: Install filepattern2
      working-directory: ${{github.workspace}}
      run: python3 setup.py install

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}
      run: python3 -m pytest tests/