name: Build And Run Test on Mac

on:
  push:
    branches: [ main ]
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  COMPILER: /usr/local/opt/llvm/bin/clang++
  CFLAGS: -I /usr/local/include -I/usr/local/opt/llvm/include 
  CXXFLAGS: -I /usr/local/include -I/usr/local/opt/llvm/include 
  LDFLAGS: -L /usr/local/lib -L/usr/local/opt/llvm/lib 
  CXX: /usr/local/opt/llvm/bin/clang++


jobs:
      
  Build_And_Run_UnitTest:
    name: Build and Run Unit Tests
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install gcc
      run: brew install gcc@8
        
    - name: Update Path
      run: |
        echo "brew --prefix llvm)/bin" >> $GITHUB_PATH
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: python3 -m pip install --upgrade wheel

    - name: Install pytest
      run: python -m pip install pytest

    - name: Install filepattern v1
      run: python -m pip install filepattern

    - name: Install filepattern2
      working-directory: ${{github.workspace}}
      run: python3 setup.py install

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}
      run: python3 -m pytest tests/